### ISSUE TITLE
Where I run the command pecl install python in my windows ?

### ISSUE THREAD

**Issue by Somino** [jparise/php-python#17]
Hi,
I want to ask you where exactly I should run the _pecl install python_ command  ?
Because I already try to run it with my _command prompt_ but I get this error : 

> 'pecl' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.

**Comment by jparise** [comment]
This appears to be a problem with your `pecl` installation. I'm afraid you'll need to address that first because it's not related to the `python` package.
