### ISSUE TITLE
Ported: Groups: php.internals php.pecl.dev 

### ISSUE THREAD

**Issue by nickl-** [jparise/php-python#6]
From:   Johannes Schlüter  Date:   Tue Mar 30 18:12:51 2010
Subject:    Dropped php3_compat.h [Fwd: [PHP-CVS] svn: /php/php-src/trunk/
ext/enchant/enchant.c ext/fileinfo/fileinfo.c
ext/intl/collator/collator_class.c ext/intl/dateformat/dateformat_class.c
ext/intl/formatter/formatter_class.c ext/intl/locale/locale_class.c
ext/intl/msgformat/msgformat_class.c ext/intl/normalizer/normalizer_class.c
ext/intl/resourcebundle/resourcebundle_class.c ext/json/json.c
ext/pdo_odbc/pdo_odbc.c ext/phar/phar.c ext/reflection/php_reflection.c
main/php.h main/php3_compat.h]
Groups: php.internals php.pecl.dev 

Hi,

I've dropped main/php3_compat.h from trunk/ the only symbol in there I
found being used was `function_entry` which is equal to
`zend_function_entry`. I've updated php-src accordingly and will do the
same in PECL tomorrow.

johannes

-------- Forwarded Message --------
From: Johannes Schlüter johannes@php.net
To: php-cvs@lists.php.net
Subject: [PHP-CVS] svn: /php/php-src/trunk/ ext/enchant/enchant.c
ext/fileinfo/fileinfo.c ext/intl/collator/collator_class.c
ext/intl/dateformat/dateformat_class.c
ext/intl/formatter/formatter_class.c ext/intl/locale/locale_class.c
ext/intl/msgformat/msgformat_class.c
ext/intl/normalizer/normalizer_class.c
ext/intl/resourcebundle/resourcebundle_class.c ext/json/json.c
ext/pdo_odbc/pdo_odbc.c ext/phar/phar.c ext/reflection/php_reflection.c
main/php.h main/php3_compat.h
Date: Tue, 30 Mar 2010 23:03:02 +0000

johannes                                 Tue, 30 Mar 2010 23:03:02 +0000

Revision: http://svn.php.net/viewvc?view=revision&revision=297208

Log:
Remove main/php3_compat.h, for that a few references to `function_entry` have
to be replaced by `zend_function_entry`.

Changed paths:
    U   php/php-src/trunk/ext/enchant/enchant.c
    U   php/php-src/trunk/ext/fileinfo/fileinfo.c
    U   php/php-src/trunk/ext/intl/collator/collator_class.c
    U   php/php-src/trunk/ext/intl/dateformat/dateformat_class.c
    U   php/php-src/trunk/ext/intl/formatter/formatter_class.c
    U   php/php-src/trunk/ext/intl/locale/locale_class.c
    U   php/php-src/trunk/ext/intl/msgformat/msgformat_class.c
    U   php/php-src/trunk/ext/intl/normalizer/normalizer_class.c
    U   php/php-src/trunk/ext/intl/resourcebundle/resourcebundle_class.c
    U   php/php-src/trunk/ext/json/json.c
    U   php/php-src/trunk/ext/pdo_odbc/pdo_odbc.c
    U   php/php-src/trunk/ext/phar/phar.c
    U   php/php-src/trunk/ext/reflection/php_reflection.c
    U   php/php-src/trunk/main/php.h
    D   php/php-src/trunk/main/php3_compat.h

**Comment by jparise** [comment]
This was fixed in ca8574c10d2c48bba810df939999a757f80b7453.
